### ISSUE TITLE
jsapi 支付

### ISSUE THREAD

**Issue by 256mywind** [thenbsp/wechat#41]
为什么用统一下单 jsapi 签名错误。

**Comment by shaukei** [comment]
<br />
<b>Fatal error</b>:  Uncaught exception 'Exception' with message '签名错误' in /usr/share/php/librarys/vendor/thenbsp/wechat/src/Payment/Unifiedorder.php:84
Stack trace:
#0 /usr/share/php/librarys/vendor/thenbsp/wechat/src/Payment/Jsapi/ConfigGenerator.php(17): Thenbsp\Wechat\Payment\Unifiedorder-&gt;getResponse()
#1 /data/web/shannon.kcis.cn/src/shannon/controllers/Wechat.php(42): Thenbsp\Wechat\Payment\Jsapi\ConfigGenerator-&gt;__construct(Object(Thenbsp\Wechat\Payment\Unifiedorder))
#2 /usr/share/php/framework/libs/Swoole/Swoole.php(914): App\Controller\Wechat-&gt;pay(NULL)
#3 /data/web/shannon.kcis.cn/src/htdocs/index.php(31): Swoole-&gt;runMVC()
#4 {main}
  thrown in <b>/usr/share/php/librarys/vendor/thenbsp/wechat/src/Payment/Unifiedorder.php</b> on line <b>84</b><br />

`代码跟例子的一样`

**Comment by shaukei** [comment]
解决了，是自己问题，没有设置商户号的key。这里要提醒一下各位
